
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TaskProgress = {
  ToDo: 'ToDo',
  InProgress: 'InProgress',
  Done: 'Done'
} as const

export type TaskProgress = (typeof TaskProgress)[keyof typeof TaskProgress]
